repos:
  - repo: local
    hooks:
      - id: swiftformat
        name: swiftformat
        language: system
        entry: swiftformat --wraparguments beforefirst --wrapcollections beforefirst
        types: [swift]
        pass_filenames: true
