substitutions:
  ssid: Wifi
  password: password
  board: board

esphome:
  name: lunarsensor
  platform: ESP32
  board: esp32dev
  includes:
    - tsl2591.h
  libraries:
    - "Adafruit TSL2591 Library"
    - https://github.com/blackhack/ESPAsyncWebServer
  platformio_options:
    board: $board
    platform: https://static.lunar.fyi/platform-espressif32-b331f75383faaa7bc8ee971b0cdb83177feb8284.zip
    platform_packages:
      - tool-esptoolpy @ https://static.lunar.fyi/esptool-dev.tar.gz

wifi:
  ssid: $ssid
  password: $password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lunar Sensor Hotspot"
    password: "lunarals23"

captive_portal:

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:

sensor:
  - platform: custom
    lambda: |-
      auto sensor = new Tsl2591();
      App.register_component(sensor);
      return {sensor};
    sensors:
      name: "Ambient Light TSL2591"
      filters:
        - filter_out: 65535
        - filter_out: nan
        - sliding_window_moving_average:
            window_size: 15
            send_every: 2
            send_first_at: 2

  - platform: tsl2561
    name: "Ambient Light TSL2561"
    update_interval: 1s
    gain: 16x
    filters:
      - filter_out: 65535
      - filter_out: nan
      - sliding_window_moving_average:
          window_size: 15
          send_every: 2
          send_first_at: 2

i2c:
  sda: 19
  scl: 23
  scan: False
  id: bus_a

web_server:
  port: 80
